version: '2.0'
services:
  app:
    depends_on:
    - redis
    build: .
    volumes:
    - .:/app
    - ./var/:/fogger
    environment:
      SOURCE_DATABASE_URL: mysql://user:pass@source:3306/source
      TARGET_DATABASE_URL: mysql://user:pass@target:3306/target
      RABBITMQ_URL: amqp://user:pass@rabbit:5672
      REDIS_URL: redis://redis
      FAKER_LOCALE: fi_FI
  worker:
    depends_on:
    - redis
    build: .
    volumes:
    - .:/app
    - ./var/:/fogger
    environment:
      SOURCE_DATABASE_URL: mysql://user:pass@source:3306/source
      TARGET_DATABASE_URL: mysql://user:pass@target:3306/target
      RABBITMQ_URL: amqp://user:pass@rabbit:5672
      REDIS_URL: redis://redis
      FAKER_LOCALE: fi_FI
    restart: always
    command: fogger:consumer --messages=50

  redis:
    image: redis:4

  source:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: source
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
    expose:
      - "3306"
    volumes:
      - ../dump/lotu-db-prod-20210218.sql:/docker-entrypoint-initdb.d/dump.sql

  target:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: target
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
    expose:
      - "3306"
