version: '2.0'
services:
  fogger:
    depends_on:
    - redis
    build: .
    volumes:
    - .:/app
    - ./var/:/fogger
    environment:
      REDIS_URI: redis://redis
      MONGO_URI: mongodb://root:example@mongo:27017
  worker:
    depends_on:
    - redis
    build: .
    volumes:
    - .:/app
    - ./var/:/fogger
    restart: always
    command: fogger:mongo:consumer
    environment:
      REDIS_URI: redis://redis
      MONGO_URI: mongodb://root:example@mongo:27017
  redis:
    image: redis:4
  gui:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
